### ISSUE TITLE
python2.7 compatibility

### ISSUE THREAD

**Issue by lpantano** [jnktsj/DNApi#3]
Hi!

I just saw this, and it's great.

We have a pipeline for small RNAseq at bcbio-nextgen. It is a very big project supporting many pipelines and a lot of people working on that. We run it in our Bioinformatic core at Harvard Chan School of Public Health.

https://github.com/chapmanb/bcbio-nextgen

I was hoping to have a compatibility version with python2.7 because all the code works on that version. Do you think it would be possible to have this?

I would be happy to help to create recipes for bioconda! 

cheers

**Comment by lpantano** [comment]
actually all examples works. Do you think the header should be changed to `/usr/bin/env python`?

**Comment by jnktsj** [comment]
Hi,

Thanks for your interest in DNApi!

Yes, the code is compatible in python 2 and 3 and can run both versions. Regarding the header `/usr/bin/env python3`, this was the remnant of the executable (`chmod +x`) DNApi for python3 because the initial code was originally written for python3 only. I changed the header to `python` in `dnapi.py` so that you can run it as the executable in your environment.

**Comment by lpantano** [comment]
thanks a lot! 
this will be great! I will create the recipe for bioconda so I can implement it quickly in our pipeline! or I'll wait if you prefer to do that.

**Comment by lpantano** [comment]
oh, you have it. great! thanks!
